name: ArcaneDonor
version: 2.0.0-SNAPSHOT
authors: [Agentred100, Jugglingman456]
description: Arcane Donor Commands
main: com.arcaneminecraft.donor.ArcaneDonor
website: https://arcaneminecraft.com/

depend: [ArcaneSurvival]

commands:
  donor:
    aliases: [donors,arcanedonor]
    description: List of donors and their commands
  slap:
    description: Slaps a palyer.
  bbycake:
    aliases: [bby]
    description: bbycake's command
  dclem:
    description: Dclem's command
  sharpshootingace:
    aliases: [sharp]
    description: SharpshootingAce!
  ytorgonak:
    aliases: [ytor]
    description: Ytorgonak!
permissions:
  # All the common permissions are in ArcaneSurvial.
  arcane.bbycake:
    description: confirms that you are bbycake
