name: ArcaneDonor
version: 2.0.0-SNAPSHOT
authors: [Agentred100, jugglingman456, SimonOrJ]
description: Arcane Donor Commands
main: com.arcaneminecraft.donor.ArcaneDonor
website: https://arcaneminecraft.com/

depend: [ArcaneSurvival]

commands:
  donor:
    aliases: [donors,arcanedonor]
    description: List of donors and their commands
  slap:
    description: Slaps a palyer.
  bbycake:
    aliases: [bby]
    description: bbycake's command
    usage: /bbycake
  dclem:
    description: Dclem's command
    usage: /DClem
  dragon_dlv:
    aliases: [dragondlv,dragon,dlv]
    description: Dragon_DLV's command
    usage: /Dragon_DLV
  monreflexion:
    aliases: [mon,monr]
    description: MonReflexion's command
    usage: /MonReflexion
  sharpshootingace:
    aliases: [sharp,sharpshooting]
    description: SharpshootingAce's command
    usage: /SharpshootingAce
  simonorj:
    aliases: [simon]
    description: SimonOrJ's command
    usage: /SimonorJ
  ytorgonak:
    aliases: [ytor]
    description: Ytorgonak!
    usage: /Ytorgonak
permissions:
  # All the common permissions are in ArcaneSurvial.
  arcane.bbycake:
    description: confirms that you are bbycake
  arcane.dragon_dlv:
    description: keeps track of death for this permission holder