name: ArcaneDonor
version: @version@
authors: [Agentred100, jugglingman456, SimonOrJ]
description: Arcane Donor Commands
main: com.arcaneminecraft.donor.ArcaneDonor
website: https://arcaneminecraft.com/
api-version: 1.13

softdepend: [ArcaneAPI]

commands:
  donor:
    aliases: [donors]
    description: List of donors and their commands
    usage: /donor

  agentred100:
    aliases: [agentred, agent]
    description: Eternal Leader Agentred100's command
    usage: /agentred100
  bbycake:
    aliases: [bby]
    description: Donor bbycake's command
    usage: /bbycake
  dclem:
    description: Donor DClem's command
    usage: /dclem
  dragon_dlv:
    aliases: [dragondlv, dragon,dlv]
    description: Donor Dragon_DLV's command
    usage: /dragon_dlv
  lordstaples:
    aliases: [lord, staples]
    description: Donor LordStaples's command
    usage: /lordstaples
  sharpshootingace:
    aliases: [sharp, sharpshooting]
    description: Donor SharpshootingAce's command
    usage: /sharpshootingace
  saeri_:
    aliases: [saeri, monr]
    description: Donor Saeri_'s command
    usage: /saeri_
  sb3:
    aliases: [sb]
    description: Donor Sb3's command
    usage: /sb3
  simonorj:
    aliases: [simon]
    description: Donor SimonOrJ's command
    usage: /simonorj
  ytorgonak:
    aliases: [ytor]
    description: Donor Ytorgonak's command
    usage: /ytorgonak

permissions:
  arcane.bbycake:
    description: Use arcane.donor.bbycake.is instead
    default: false
    children:
      arcane.donor.bbycake.is: true
  arcane.donor.bbycake.is:
    description: This person is bbycake
    default: false

  arcane.donor.dragon_dlv.is:
    description: This person is Dragon_DLV
    default: false

  arcane.donor.sb3.mod:
    description: Allows modification of word list
    default: op
