name: ArcaneDonor
version: @version@
authors: [Agentred100, jugglingman456, SimonOrJ]
description: Arcane Donor Commands
main: com.arcaneminecraft.donor.ArcaneDonor
website: https://arcaneminecraft.com/
api-version: 1.13

depend: [ArcaneAPI]

commands:
  donor:
    aliases: [donors]
    description: List of donors and their commands
    usage: /donor [page]

  bbycake:
    aliases: [bby]
    description: Donor bbycake's command
    usage: /bbycake
  dclem:
    description: Donor DClem's command
    usage: /dclem
  dragon_dlv:
    aliases: [dragondlv, dragon,dlv]
    description: Donor Dragon_DLV's command
    usage: /dragon_dlv
  sharpshootingace:
    aliases: [sharp, sharpshooting]
    description: Donor SharpshootingAce's command
    usage: /sharpshootingace
  saeri_:
    aliases: [saeri, monr]
    description: Donor MonReflexion's command
    usage: /monreflexion
  simonorj:
    aliases: [simon]
    description: Donor SimonOrJ's command
    usage: /simonorj
  ytorgonak:
    aliases: [ytor]
    description: Donor Ytorgonak's command
    usage: /ytorgonak

permissions:
  arcane.bbycake:
    description: confirms that you are bbycake
    default: false
